#!/bin/bash -e

cd /sys/class/backlight/backlight*

## Unpatched kernel
## /sys/class/backlight/backlight/brightness

## Chrome OS 3.8.11 kernel (archlinuxarm.org linux-peach package)
## /sys/class/backlight/backlight.12/brightness

pwd | grep 12 && {
  echo "Patched kernel detected. Valid argument: 50-2800"
  [[ $1 -ge 50 ]] || exit
  [[ $1 -le 2800 ]] || exit
  echo $1 > brightness && echo "Brightness is now: $1"
  exit 0
}

echo "Unpatched kernel detected. Valid argument: 1-7"
[[ $1 -ge 1 ]]
[[ $1 -le 7 ]]
echo $1 > brightness && echo "Brightness is now: $1"
