#!/bin/bash -e

## NOTES
echo "7 is really bright, 5 is less bright, 1 is very dim"
echo "i would not try 0, this may render your installation useless, however,"
echo "brightness setting does not affect u-boot screen, so it won't really brick"
echo "your device to do this, just make it so that retrieving files might be"
echo "impossible"
echo
echo "Press enter to continue"
read -p "... " WAIT

## CHANGE BRIGHTNESS WHILE STILL AT THE COMMAND LINE
nano /sys/devices/platform/backlight/backlight/backlight/brightness
