#!/bin/bash -e

## Randomization options
# $(openssl rand -hex 6 | sed -e 's/\(..\)/:\1/g2')
# $(hexdump -n 6 -v -e '6/1 "%02X"' /dev/urandom | sed -e 's/\(..\)/:\1/g2')

## Format
## 1a:2b:3c:4d:5e:6f

ip link set mlan0 down

read -p "Enter a MAC ID to spoof (or Enter for random): " SPOOF
if [ -z "$SPOOF" ]; then
  SPOOF=$(openssl rand -hex 6 | sed -e 's/\(..\)/:\1/g2')
fi

ip link set dev mlan0 address $SPOOF
ip link set mlan0 up
