#!/bin/bash -e

## This script depends on the Arch Linux package "xorg-xinput"

## How to reduce mouse sensitivity
#MOUSE=$(xinput | grep -i 'Mouse' | grep 'pointer' | cut -c55-56)
#PROP=$(xinput list-props $MOUSE | grep 'Accel Speed (' | cut -c24-26)
#xinput set-prop $MOUSE $PROP -1

## If there's a mouse, then disable the trackpad
TRACKPAD=$(xinput | grep -i 'pad' | cut -c55-56)
xinput | grep -iq 'Mouse' \
    && xinput disable $TRACKPAD \
    && echo "Trackpad disabled." \
|| {
  ## There's no mouse, so enable the trackpad
    xinput enable $TRACKPAD \
    && echo "Trackpad enabled."
}
